### ISSUE TITLE
Crash on roll

### ISSUE THREAD

**Issue by StubbsPKS** [Astrydax/SWEotE-Discord-Dice-Roller#48]
Just cloned this, installed node on my Win 10 box and gave it a shot. 

The npm install gives me :
> npm WARN discord.js@11.0.0 requires a peer of erlpack@hammerandchisel/erlpack#master but none was installed.
> npm WARN discord.js@11.0.0 requires a peer of node-opus@^0.2.0 but none was installed.
> npm WARN discord.js@11.0.0 requires a peer of opusscript@^0.0.1 but none was installed.
> npm WARN discord.js@11.0.0 requires a peer of uws@^0.12.0 but none was installed.
> npm WARN edge-of-the-empire-dice-roller@1.4.5 No repository field.

Figured I'd give running it a shot anyway. The bot is present in the server, and when I try the example roll of `!roll yyyggbbd "Blast Him!"` in the discord channel , I get the following in my terminal:

```
[ 'yyyggbbd', '"Blast', 'Him!"' ]
Beg: 1 End: 2
params: "Blast
params: Him!"
params: undefined
Rolling dice for StubbsPKS (Charlie Kelly)
Rolling 1 Proficiency Dice.
Success
D:\Star Wars\Dice Roller Source\modules\roll.js:388
        diceResult.face += print("ys", message);
                           ^

TypeError: print is not a function
    at rollYellow (D:\Star Wars\Dice Roller Source\modules\roll.js:388:28)
    at rollDice (D:\Star Wars\Dice Roller Source\modules\roll.js:134:28)
    at Object.roll (D:\Star Wars\Dice Roller Source\modules\roll.js:49:11)
    at Client.bot.on.message (D:\Star Wars\Dice Roller Source\bot.js:165:10)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (D:\Star Wars\Dice Roller Source\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (D:\Star Wars\Dice Roller Source\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:120:65)
    at WebSocketManager.eventMessage (D:\Star Wars\Dice Roller Source\node_modules\discord.js\src\client\websocket\WebSocketManager.js:273:31)
    at WebSocket.onMessage (D:\Star Wars\Dice Roller Source\node_modules\ws\lib\WebSocket.js:442:14)
Press any key to continue . . .
```

I'm assuming this is due to the warnings with NPM, but not entirely sure how to resolve them.

**Comment by SkyJedi** [comment]
try from this repo  https://github.com/SkyJedi/SWEotE-Discord-Dice-Roller

**Comment by StubbsPKS** [comment]
@SkyJedi That worked much better. Just need to get the custom emojis installed now. Thanks a bunch!

**Comment by SkyJedi** [comment]
this looks like the same issue of the print variable getting lost with <1.5.1
