### ISSUE TITLE
botStats.daily is undefined

### ISSUE THREAD

**Issue by txmoose** [Astrydax/SWEotE-Discord-Dice-Roller#52]
Admittedly, I'm not knowledgeable with JS, but I've followed the install instructions  in the README.md and this is what I'm getting.  Any thoughts?  The bot crashes on this.

Thanks.

```
@<discord_username> Tue Nov 28 2017 21:37:17 GMT-0500 (EST)
help
/home/<user>/git/nodejs/SWEotE-Discord-Dice-Roller-master/bot.js:168
      botStats.daily.help++;
               ^

TypeError: Cannot read property 'daily' of undefined
    at Client.bot.on.message (/home/<user>/git/nodejs/SWEotE-Discord-Dice-Roller-master/bot.js:168:16)
    at Client.emit (events.js:159:13)
    at MessageCreateHandler.handle (/home/<user>/git/nodejs/SWEotE-Discord-Dice-Roller-master/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/<user>/git/nodejs/SWEotE-Discord-Dice-Roller-master/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/home/<user>/git/nodejs/SWEotE-Discord-Dice-Roller-master/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (/home/<user>/git/nodejs/SWEotE-Discord-Dice-Roller-master/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:293:17)
    at WebSocketClient.internalOnMessage (/home/<user>/git/nodejs/SWEotE-Discord-Dice-Roller-master/node_modules/uws/uws.js:103:17)
    at native.client.group.onMessage (/home/<user>/git/nodejs/SWEotE-Discord-Dice-Roller-master/node_modules/uws/uws.js:57:15)
```

**Comment by SkyJedi** [comment]
bot got recoded, delete botstats and diceresults  variable from your
firebase database and reboot

**Comment by txmoose** [comment]
I stood up a new firebase project for this as I've never used it before. Do you have steps to set up firebase for this? 

I upgraded from a much earlier version to this latest. Something like .9?

**Comment by SkyJedi** [comment]
https://github.com/SkyJedi/SWEotE-Discord-Dice-Roller

in the readme.

Sorry i gotta crash right now, i can help more in the morning though

-Sky

**Comment by txmoose** [comment]
Oh I didn't realize there was another project on this! Thanks for the insanely quick help. I got it from here. Awesome work!
